/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHallOfFameRouteImport } from './routes/_authenticated/hall-of-fame'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTournamentIdRouteImport } from './routes/_authenticated/tournament.$id'
import { Route as AuthenticatedTournamentIdLineupRouteImport } from './routes/_authenticated/tournament.$id.lineup'
import { Route as AuthenticatedAdminTournamentIdFieldRouteImport } from './routes/_authenticated/admin.tournament.$id.field'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHallOfFameRoute = AuthenticatedHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTournamentIdRoute =
  AuthenticatedTournamentIdRouteImport.update({
    id: '/tournament/$id',
    path: '/tournament/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTournamentIdLineupRoute =
  AuthenticatedTournamentIdLineupRouteImport.update({
    id: '/lineup',
    path: '/lineup',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedAdminTournamentIdFieldRoute =
  AuthenticatedAdminTournamentIdFieldRouteImport.update({
    id: '/admin/tournament/$id/field',
    path: '/admin/tournament/$id/field',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/_authenticated/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/archive'
    | '/hall-of-fame'
    | '/home'
    | '/profile'
    | '/stats'
    | '/tournament/$id'
    | '/admin/'
    | '/tournament/$id/lineup'
    | '/admin/tournament/$id/field'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/archive'
    | '/hall-of-fame'
    | '/home'
    | '/profile'
    | '/stats'
    | '/tournament/$id'
    | '/admin'
    | '/tournament/$id/lineup'
    | '/admin/tournament/$id/field'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/archive'
    | '/_authenticated/hall-of-fame'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/stats'
    | '/_authenticated/tournament/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/tournament/$id/lineup'
    | '/_authenticated/admin/tournament/$id/field'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hall-of-fame': {
      id: '/_authenticated/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof AuthenticatedHallOfFameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournament/$id': {
      id: '/_authenticated/tournament/$id'
      path: '/tournament/$id'
      fullPath: '/tournament/$id'
      preLoaderRoute: typeof AuthenticatedTournamentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournament/$id/lineup': {
      id: '/_authenticated/tournament/$id/lineup'
      path: '/lineup'
      fullPath: '/tournament/$id/lineup'
      preLoaderRoute: typeof AuthenticatedTournamentIdLineupRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/admin/tournament/$id/field': {
      id: '/_authenticated/admin/tournament/$id/field'
      path: '/admin/tournament/$id/field'
      fullPath: '/admin/tournament/$id/field'
      preLoaderRoute: typeof AuthenticatedAdminTournamentIdFieldRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedTournamentIdRouteChildren {
  AuthenticatedTournamentIdLineupRoute: typeof AuthenticatedTournamentIdLineupRoute
}

const AuthenticatedTournamentIdRouteChildren: AuthenticatedTournamentIdRouteChildren =
  {
    AuthenticatedTournamentIdLineupRoute: AuthenticatedTournamentIdLineupRoute,
  }

const AuthenticatedTournamentIdRouteWithChildren =
  AuthenticatedTournamentIdRoute._addFileChildren(
    AuthenticatedTournamentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedHallOfFameRoute: typeof AuthenticatedHallOfFameRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTournamentIdRoute: typeof AuthenticatedTournamentIdRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTournamentIdFieldRoute: typeof AuthenticatedAdminTournamentIdFieldRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedHallOfFameRoute: AuthenticatedHallOfFameRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTournamentIdRoute: AuthenticatedTournamentIdRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTournamentIdFieldRoute:
    AuthenticatedAdminTournamentIdFieldRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
