/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForceUpdatePasswordRouteImport } from './routes/force-update-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogPostIdRouteImport } from './routes/blog.$postId'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHallOfFameRouteImport } from './routes/_authenticated/hall-of-fame'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBlogIndexRouteImport } from './routes/_authenticated/blog.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedTournamentIdRouteImport } from './routes/_authenticated/tournament.$id'
import { Route as AuthenticatedBlogNewRouteImport } from './routes/_authenticated/blog.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminBlogWriterRouteImport } from './routes/_authenticated/admin.blog-writer'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksPickReminderRouteImport } from './routes/api/public/hooks/pick-reminder'
import { Route as ApiPublicHooksNewUserSignupRouteImport } from './routes/api/public/hooks/new-user-signup'
import { Route as AuthenticatedTournamentIdStatsRouteImport } from './routes/_authenticated/tournament.$id.stats'
import { Route as AuthenticatedTournamentIdLineupRouteImport } from './routes/_authenticated/tournament.$id.lineup'
import { Route as AuthenticatedTournamentIdLeaderboardRouteImport } from './routes/_authenticated/tournament.$id.leaderboard'
import { Route as AuthenticatedBlogPostIdEditRouteImport } from './routes/_authenticated/blog.$postId.edit'
import { Route as AuthenticatedTournamentIdBlogNewRouteImport } from './routes/_authenticated/tournament.$id.blog.new'
import { Route as AuthenticatedAdminTournamentIdFieldRouteImport } from './routes/_authenticated/admin.tournament.$id.field'
import { Route as AuthenticatedTournamentIdBlogPostIdIndexRouteImport } from './routes/_authenticated/tournament.$id.blog.$postId.index'
import { Route as AuthenticatedTournamentIdBlogPostIdEditRouteImport } from './routes/_authenticated/tournament.$id.blog.$postId.edit'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForceUpdatePasswordRoute = ForceUpdatePasswordRouteImport.update({
  id: '/force-update-password',
  path: '/force-update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHallOfFameRoute = AuthenticatedHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlogIndexRoute = AuthenticatedBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTournamentIdRoute =
  AuthenticatedTournamentIdRouteImport.update({
    id: '/tournament/$id',
    path: '/tournament/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlogNewRoute = AuthenticatedBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBlogWriterRoute =
  AuthenticatedAdminBlogWriterRouteImport.update({
    id: '/blog-writer',
    path: '/blog-writer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPickReminderRoute =
  ApiPublicHooksPickReminderRouteImport.update({
    id: '/api/public/hooks/pick-reminder',
    path: '/api/public/hooks/pick-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNewUserSignupRoute =
  ApiPublicHooksNewUserSignupRouteImport.update({
    id: '/api/public/hooks/new-user-signup',
    path: '/api/public/hooks/new-user-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTournamentIdStatsRoute =
  AuthenticatedTournamentIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedTournamentIdLineupRoute =
  AuthenticatedTournamentIdLineupRouteImport.update({
    id: '/lineup',
    path: '/lineup',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedTournamentIdLeaderboardRoute =
  AuthenticatedTournamentIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedBlogPostIdEditRoute =
  AuthenticatedBlogPostIdEditRouteImport.update({
    id: '/blog/$postId/edit',
    path: '/blog/$postId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTournamentIdBlogNewRoute =
  AuthenticatedTournamentIdBlogNewRouteImport.update({
    id: '/blog/new',
    path: '/blog/new',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedAdminTournamentIdFieldRoute =
  AuthenticatedAdminTournamentIdFieldRouteImport.update({
    id: '/tournament/$id/field',
    path: '/tournament/$id/field',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTournamentIdBlogPostIdIndexRoute =
  AuthenticatedTournamentIdBlogPostIdIndexRouteImport.update({
    id: '/blog/$postId/',
    path: '/blog/$postId/',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedTournamentIdBlogPostIdEditRoute =
  AuthenticatedTournamentIdBlogPostIdEditRouteImport.update({
    id: '/blog/$postId/edit',
    path: '/blog/$postId/edit',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/force-update-password': typeof ForceUpdatePasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/archive': typeof AuthenticatedArchiveRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/blog-writer': typeof AuthenticatedAdminBlogWriterRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/blog/': typeof AuthenticatedBlogIndexRoute
  '/blog/$postId/edit': typeof AuthenticatedBlogPostIdEditRoute
  '/tournament/$id/leaderboard': typeof AuthenticatedTournamentIdLeaderboardRoute
  '/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/tournament/$id/stats': typeof AuthenticatedTournamentIdStatsRoute
  '/api/public/hooks/new-user-signup': typeof ApiPublicHooksNewUserSignupRoute
  '/api/public/hooks/pick-reminder': typeof ApiPublicHooksPickReminderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
  '/tournament/$id/blog/new': typeof AuthenticatedTournamentIdBlogNewRoute
  '/tournament/$id/blog/$postId/edit': typeof AuthenticatedTournamentIdBlogPostIdEditRoute
  '/tournament/$id/blog/$postId/': typeof AuthenticatedTournamentIdBlogPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/force-update-password': typeof ForceUpdatePasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/blog-writer': typeof AuthenticatedAdminBlogWriterRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/blog/new': typeof AuthenticatedBlogNewRoute
  '/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/blog': typeof AuthenticatedBlogIndexRoute
  '/blog/$postId/edit': typeof AuthenticatedBlogPostIdEditRoute
  '/tournament/$id/leaderboard': typeof AuthenticatedTournamentIdLeaderboardRoute
  '/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/tournament/$id/stats': typeof AuthenticatedTournamentIdStatsRoute
  '/api/public/hooks/new-user-signup': typeof ApiPublicHooksNewUserSignupRoute
  '/api/public/hooks/pick-reminder': typeof ApiPublicHooksPickReminderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
  '/tournament/$id/blog/new': typeof AuthenticatedTournamentIdBlogNewRoute
  '/tournament/$id/blog/$postId/edit': typeof AuthenticatedTournamentIdBlogPostIdEditRoute
  '/tournament/$id/blog/$postId': typeof AuthenticatedTournamentIdBlogPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/force-update-password': typeof ForceUpdatePasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/blog-writer': typeof AuthenticatedAdminBlogWriterRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/blog/new': typeof AuthenticatedBlogNewRoute
  '/_authenticated/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/blog/': typeof AuthenticatedBlogIndexRoute
  '/_authenticated/blog/$postId/edit': typeof AuthenticatedBlogPostIdEditRoute
  '/_authenticated/tournament/$id/leaderboard': typeof AuthenticatedTournamentIdLeaderboardRoute
  '/_authenticated/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/_authenticated/tournament/$id/stats': typeof AuthenticatedTournamentIdStatsRoute
  '/api/public/hooks/new-user-signup': typeof ApiPublicHooksNewUserSignupRoute
  '/api/public/hooks/pick-reminder': typeof ApiPublicHooksPickReminderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
  '/_authenticated/tournament/$id/blog/new': typeof AuthenticatedTournamentIdBlogNewRoute
  '/_authenticated/tournament/$id/blog/$postId/edit': typeof AuthenticatedTournamentIdBlogPostIdEditRoute
  '/_authenticated/tournament/$id/blog/$postId/': typeof AuthenticatedTournamentIdBlogPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/force-update-password'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/welcome'
    | '/admin'
    | '/archive'
    | '/hall-of-fame'
    | '/home'
    | '/profile'
    | '/rules'
    | '/stats'
    | '/blog/$postId'
    | '/email/unsubscribe'
    | '/admin/blog-writer'
    | '/admin/users'
    | '/blog/new'
    | '/tournament/$id'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/blog/'
    | '/blog/$postId/edit'
    | '/tournament/$id/leaderboard'
    | '/tournament/$id/lineup'
    | '/tournament/$id/stats'
    | '/api/public/hooks/new-user-signup'
    | '/api/public/hooks/pick-reminder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/tournament/$id/field'
    | '/tournament/$id/blog/new'
    | '/tournament/$id/blog/$postId/edit'
    | '/tournament/$id/blog/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/force-update-password'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/welcome'
    | '/archive'
    | '/hall-of-fame'
    | '/home'
    | '/profile'
    | '/rules'
    | '/stats'
    | '/blog/$postId'
    | '/email/unsubscribe'
    | '/admin/blog-writer'
    | '/admin/users'
    | '/blog/new'
    | '/tournament/$id'
    | '/lovable/email/suppression'
    | '/admin'
    | '/blog'
    | '/blog/$postId/edit'
    | '/tournament/$id/leaderboard'
    | '/tournament/$id/lineup'
    | '/tournament/$id/stats'
    | '/api/public/hooks/new-user-signup'
    | '/api/public/hooks/pick-reminder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/tournament/$id/field'
    | '/tournament/$id/blog/new'
    | '/tournament/$id/blog/$postId/edit'
    | '/tournament/$id/blog/$postId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/force-update-password'
    | '/login'
    | '/reset-password'
    | '/unsubscribe'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/archive'
    | '/_authenticated/hall-of-fame'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/rules'
    | '/_authenticated/stats'
    | '/blog/$postId'
    | '/email/unsubscribe'
    | '/_authenticated/admin/blog-writer'
    | '/_authenticated/admin/users'
    | '/_authenticated/blog/new'
    | '/_authenticated/tournament/$id'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/blog/'
    | '/_authenticated/blog/$postId/edit'
    | '/_authenticated/tournament/$id/leaderboard'
    | '/_authenticated/tournament/$id/lineup'
    | '/_authenticated/tournament/$id/stats'
    | '/api/public/hooks/new-user-signup'
    | '/api/public/hooks/pick-reminder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/tournament/$id/field'
    | '/_authenticated/tournament/$id/blog/new'
    | '/_authenticated/tournament/$id/blog/$postId/edit'
    | '/_authenticated/tournament/$id/blog/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForceUpdatePasswordRoute: typeof ForceUpdatePasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WelcomeRoute: typeof WelcomeRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksNewUserSignupRoute: typeof ApiPublicHooksNewUserSignupRoute
  ApiPublicHooksPickReminderRoute: typeof ApiPublicHooksPickReminderRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-update-password': {
      id: '/force-update-password'
      path: '/force-update-password'
      fullPath: '/force-update-password'
      preLoaderRoute: typeof ForceUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hall-of-fame': {
      id: '/_authenticated/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof AuthenticatedHallOfFameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog/': {
      id: '/_authenticated/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof AuthenticatedBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tournament/$id': {
      id: '/_authenticated/tournament/$id'
      path: '/tournament/$id'
      fullPath: '/tournament/$id'
      preLoaderRoute: typeof AuthenticatedTournamentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog/new': {
      id: '/_authenticated/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof AuthenticatedBlogNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog-writer': {
      id: '/_authenticated/admin/blog-writer'
      path: '/blog-writer'
      fullPath: '/admin/blog-writer'
      preLoaderRoute: typeof AuthenticatedAdminBlogWriterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pick-reminder': {
      id: '/api/public/hooks/pick-reminder'
      path: '/api/public/hooks/pick-reminder'
      fullPath: '/api/public/hooks/pick-reminder'
      preLoaderRoute: typeof ApiPublicHooksPickReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/new-user-signup': {
      id: '/api/public/hooks/new-user-signup'
      path: '/api/public/hooks/new-user-signup'
      fullPath: '/api/public/hooks/new-user-signup'
      preLoaderRoute: typeof ApiPublicHooksNewUserSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tournament/$id/stats': {
      id: '/_authenticated/tournament/$id/stats'
      path: '/stats'
      fullPath: '/tournament/$id/stats'
      preLoaderRoute: typeof AuthenticatedTournamentIdStatsRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/tournament/$id/lineup': {
      id: '/_authenticated/tournament/$id/lineup'
      path: '/lineup'
      fullPath: '/tournament/$id/lineup'
      preLoaderRoute: typeof AuthenticatedTournamentIdLineupRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/tournament/$id/leaderboard': {
      id: '/_authenticated/tournament/$id/leaderboard'
      path: '/leaderboard'
      fullPath: '/tournament/$id/leaderboard'
      preLoaderRoute: typeof AuthenticatedTournamentIdLeaderboardRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/blog/$postId/edit': {
      id: '/_authenticated/blog/$postId/edit'
      path: '/blog/$postId/edit'
      fullPath: '/blog/$postId/edit'
      preLoaderRoute: typeof AuthenticatedBlogPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournament/$id/blog/new': {
      id: '/_authenticated/tournament/$id/blog/new'
      path: '/blog/new'
      fullPath: '/tournament/$id/blog/new'
      preLoaderRoute: typeof AuthenticatedTournamentIdBlogNewRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/admin/tournament/$id/field': {
      id: '/_authenticated/admin/tournament/$id/field'
      path: '/tournament/$id/field'
      fullPath: '/admin/tournament/$id/field'
      preLoaderRoute: typeof AuthenticatedAdminTournamentIdFieldRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tournament/$id/blog/$postId/': {
      id: '/_authenticated/tournament/$id/blog/$postId/'
      path: '/blog/$postId'
      fullPath: '/tournament/$id/blog/$postId/'
      preLoaderRoute: typeof AuthenticatedTournamentIdBlogPostIdIndexRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/tournament/$id/blog/$postId/edit': {
      id: '/_authenticated/tournament/$id/blog/$postId/edit'
      path: '/blog/$postId/edit'
      fullPath: '/tournament/$id/blog/$postId/edit'
      preLoaderRoute: typeof AuthenticatedTournamentIdBlogPostIdEditRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogWriterRoute: typeof AuthenticatedAdminBlogWriterRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTournamentIdFieldRoute: typeof AuthenticatedAdminTournamentIdFieldRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogWriterRoute: AuthenticatedAdminBlogWriterRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTournamentIdFieldRoute:
    AuthenticatedAdminTournamentIdFieldRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTournamentIdRouteChildren {
  AuthenticatedTournamentIdLeaderboardRoute: typeof AuthenticatedTournamentIdLeaderboardRoute
  AuthenticatedTournamentIdLineupRoute: typeof AuthenticatedTournamentIdLineupRoute
  AuthenticatedTournamentIdStatsRoute: typeof AuthenticatedTournamentIdStatsRoute
  AuthenticatedTournamentIdBlogNewRoute: typeof AuthenticatedTournamentIdBlogNewRoute
  AuthenticatedTournamentIdBlogPostIdEditRoute: typeof AuthenticatedTournamentIdBlogPostIdEditRoute
  AuthenticatedTournamentIdBlogPostIdIndexRoute: typeof AuthenticatedTournamentIdBlogPostIdIndexRoute
}

const AuthenticatedTournamentIdRouteChildren: AuthenticatedTournamentIdRouteChildren =
  {
    AuthenticatedTournamentIdLeaderboardRoute:
      AuthenticatedTournamentIdLeaderboardRoute,
    AuthenticatedTournamentIdLineupRoute: AuthenticatedTournamentIdLineupRoute,
    AuthenticatedTournamentIdStatsRoute: AuthenticatedTournamentIdStatsRoute,
    AuthenticatedTournamentIdBlogNewRoute:
      AuthenticatedTournamentIdBlogNewRoute,
    AuthenticatedTournamentIdBlogPostIdEditRoute:
      AuthenticatedTournamentIdBlogPostIdEditRoute,
    AuthenticatedTournamentIdBlogPostIdIndexRoute:
      AuthenticatedTournamentIdBlogPostIdIndexRoute,
  }

const AuthenticatedTournamentIdRouteWithChildren =
  AuthenticatedTournamentIdRoute._addFileChildren(
    AuthenticatedTournamentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedHallOfFameRoute: typeof AuthenticatedHallOfFameRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedBlogNewRoute: typeof AuthenticatedBlogNewRoute
  AuthenticatedTournamentIdRoute: typeof AuthenticatedTournamentIdRouteWithChildren
  AuthenticatedBlogIndexRoute: typeof AuthenticatedBlogIndexRoute
  AuthenticatedBlogPostIdEditRoute: typeof AuthenticatedBlogPostIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedHallOfFameRoute: AuthenticatedHallOfFameRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedBlogNewRoute: AuthenticatedBlogNewRoute,
  AuthenticatedTournamentIdRoute: AuthenticatedTournamentIdRouteWithChildren,
  AuthenticatedBlogIndexRoute: AuthenticatedBlogIndexRoute,
  AuthenticatedBlogPostIdEditRoute: AuthenticatedBlogPostIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForceUpdatePasswordRoute: ForceUpdatePasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WelcomeRoute: WelcomeRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksNewUserSignupRoute: ApiPublicHooksNewUserSignupRoute,
  ApiPublicHooksPickReminderRoute: ApiPublicHooksPickReminderRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
