/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHallOfFameRouteImport } from './routes/_authenticated/hall-of-fame'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTournamentIdRouteImport } from './routes/_authenticated/tournament.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedTournamentIdLineupRouteImport } from './routes/_authenticated/tournament.$id.lineup'
import { Route as AuthenticatedTournamentIdLeaderboardRouteImport } from './routes/_authenticated/tournament.$id.leaderboard'
import { Route as AuthenticatedTournamentIdBlogNewRouteImport } from './routes/_authenticated/tournament.$id.blog.new'
import { Route as AuthenticatedAdminTournamentIdFieldRouteImport } from './routes/_authenticated/admin.tournament.$id.field'
import { Route as AuthenticatedTournamentIdBlogPostIdEditRouteImport } from './routes/_authenticated/tournament.$id.blog.$postId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHallOfFameRoute = AuthenticatedHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTournamentIdRoute =
  AuthenticatedTournamentIdRouteImport.update({
    id: '/tournament/$id',
    path: '/tournament/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTournamentIdLineupRoute =
  AuthenticatedTournamentIdLineupRouteImport.update({
    id: '/lineup',
    path: '/lineup',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedTournamentIdLeaderboardRoute =
  AuthenticatedTournamentIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedTournamentIdBlogNewRoute =
  AuthenticatedTournamentIdBlogNewRouteImport.update({
    id: '/blog/new',
    path: '/blog/new',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)
const AuthenticatedAdminTournamentIdFieldRoute =
  AuthenticatedAdminTournamentIdFieldRouteImport.update({
    id: '/tournament/$id/field',
    path: '/tournament/$id/field',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTournamentIdBlogPostIdEditRoute =
  AuthenticatedTournamentIdBlogPostIdEditRouteImport.update({
    id: '/blog/$postId/edit',
    path: '/blog/$postId/edit',
    getParentRoute: () => AuthenticatedTournamentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/archive': typeof AuthenticatedArchiveRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tournament/$id/leaderboard': typeof AuthenticatedTournamentIdLeaderboardRoute
  '/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
  '/tournament/$id/blog/new': typeof AuthenticatedTournamentIdBlogNewRoute
  '/tournament/$id/blog/$postId/edit': typeof AuthenticatedTournamentIdBlogPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tournament/$id/leaderboard': typeof AuthenticatedTournamentIdLeaderboardRoute
  '/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
  '/tournament/$id/blog/new': typeof AuthenticatedTournamentIdBlogNewRoute
  '/tournament/$id/blog/$postId/edit': typeof AuthenticatedTournamentIdBlogPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/hall-of-fame': typeof AuthenticatedHallOfFameRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/tournament/$id': typeof AuthenticatedTournamentIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tournament/$id/leaderboard': typeof AuthenticatedTournamentIdLeaderboardRoute
  '/_authenticated/tournament/$id/lineup': typeof AuthenticatedTournamentIdLineupRoute
  '/_authenticated/admin/tournament/$id/field': typeof AuthenticatedAdminTournamentIdFieldRoute
  '/_authenticated/tournament/$id/blog/new': typeof AuthenticatedTournamentIdBlogNewRoute
  '/_authenticated/tournament/$id/blog/$postId/edit': typeof AuthenticatedTournamentIdBlogPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/archive'
    | '/hall-of-fame'
    | '/home'
    | '/profile'
    | '/stats'
    | '/admin/users'
    | '/tournament/$id'
    | '/admin/'
    | '/tournament/$id/leaderboard'
    | '/tournament/$id/lineup'
    | '/admin/tournament/$id/field'
    | '/tournament/$id/blog/new'
    | '/tournament/$id/blog/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/archive'
    | '/hall-of-fame'
    | '/home'
    | '/profile'
    | '/stats'
    | '/admin/users'
    | '/tournament/$id'
    | '/admin'
    | '/tournament/$id/leaderboard'
    | '/tournament/$id/lineup'
    | '/admin/tournament/$id/field'
    | '/tournament/$id/blog/new'
    | '/tournament/$id/blog/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/archive'
    | '/_authenticated/hall-of-fame'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/stats'
    | '/_authenticated/admin/users'
    | '/_authenticated/tournament/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/tournament/$id/leaderboard'
    | '/_authenticated/tournament/$id/lineup'
    | '/_authenticated/admin/tournament/$id/field'
    | '/_authenticated/tournament/$id/blog/new'
    | '/_authenticated/tournament/$id/blog/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hall-of-fame': {
      id: '/_authenticated/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof AuthenticatedHallOfFameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tournament/$id': {
      id: '/_authenticated/tournament/$id'
      path: '/tournament/$id'
      fullPath: '/tournament/$id'
      preLoaderRoute: typeof AuthenticatedTournamentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tournament/$id/lineup': {
      id: '/_authenticated/tournament/$id/lineup'
      path: '/lineup'
      fullPath: '/tournament/$id/lineup'
      preLoaderRoute: typeof AuthenticatedTournamentIdLineupRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/tournament/$id/leaderboard': {
      id: '/_authenticated/tournament/$id/leaderboard'
      path: '/leaderboard'
      fullPath: '/tournament/$id/leaderboard'
      preLoaderRoute: typeof AuthenticatedTournamentIdLeaderboardRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/tournament/$id/blog/new': {
      id: '/_authenticated/tournament/$id/blog/new'
      path: '/blog/new'
      fullPath: '/tournament/$id/blog/new'
      preLoaderRoute: typeof AuthenticatedTournamentIdBlogNewRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
    '/_authenticated/admin/tournament/$id/field': {
      id: '/_authenticated/admin/tournament/$id/field'
      path: '/tournament/$id/field'
      fullPath: '/admin/tournament/$id/field'
      preLoaderRoute: typeof AuthenticatedAdminTournamentIdFieldRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tournament/$id/blog/$postId/edit': {
      id: '/_authenticated/tournament/$id/blog/$postId/edit'
      path: '/blog/$postId/edit'
      fullPath: '/tournament/$id/blog/$postId/edit'
      preLoaderRoute: typeof AuthenticatedTournamentIdBlogPostIdEditRouteImport
      parentRoute: typeof AuthenticatedTournamentIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTournamentIdFieldRoute: typeof AuthenticatedAdminTournamentIdFieldRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTournamentIdFieldRoute:
    AuthenticatedAdminTournamentIdFieldRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTournamentIdRouteChildren {
  AuthenticatedTournamentIdLeaderboardRoute: typeof AuthenticatedTournamentIdLeaderboardRoute
  AuthenticatedTournamentIdLineupRoute: typeof AuthenticatedTournamentIdLineupRoute
  AuthenticatedTournamentIdBlogNewRoute: typeof AuthenticatedTournamentIdBlogNewRoute
  AuthenticatedTournamentIdBlogPostIdEditRoute: typeof AuthenticatedTournamentIdBlogPostIdEditRoute
}

const AuthenticatedTournamentIdRouteChildren: AuthenticatedTournamentIdRouteChildren =
  {
    AuthenticatedTournamentIdLeaderboardRoute:
      AuthenticatedTournamentIdLeaderboardRoute,
    AuthenticatedTournamentIdLineupRoute: AuthenticatedTournamentIdLineupRoute,
    AuthenticatedTournamentIdBlogNewRoute:
      AuthenticatedTournamentIdBlogNewRoute,
    AuthenticatedTournamentIdBlogPostIdEditRoute:
      AuthenticatedTournamentIdBlogPostIdEditRoute,
  }

const AuthenticatedTournamentIdRouteWithChildren =
  AuthenticatedTournamentIdRoute._addFileChildren(
    AuthenticatedTournamentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedHallOfFameRoute: typeof AuthenticatedHallOfFameRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTournamentIdRoute: typeof AuthenticatedTournamentIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedHallOfFameRoute: AuthenticatedHallOfFameRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTournamentIdRoute: AuthenticatedTournamentIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
